### ISSUE TITLE
Documentation "how to set up mockito-core as a Java agent" for Gradle Kotlin should be improved

### ISSUE THREAD

**Issue by tdltdl** [mockito/mockito#3584]
The current version of documentation recommends to set the jvmArgs as the jvmArgs
```
tasks {
    test {
        jvmArgs("-javaagent:${mockitoAgent.asPath}")
     }
}
``` 

This is working when only Mockito agent is in use. As soon as another agent is expected (example for code coverage), this will fail as this overrides any previously registered agent. It will also remove all previously set jvmArgs.

_**To reproduce:**_
Both from IntelliJ
* Run tests requiring Mockito agent coinfigured as documented, it will succeed
* Re-run the same test with coverage, test will fail

_**Fix**_
The fix is trivial, instead of setting the jvmArgs, we need to add the entry instead.
```
tasks {
    test {
        jvmArgs.add("-javaagent:${mockitoAgent.asPath}")
     }
}
```
Tested with Grade 8.12 and Mockito 5.15.2

See https://github.com/mockito/mockito/blob/83ee69b8b927e166f7a8acf6e789a26a58f63567/mockito-core/src/main/java/org/mockito/Mockito.java#L194

**Comment by philipp94831** [comment]
When using `jvmArgs.add("-javaagent:${mockitoAgent.asPath}")`, only the IntelliJ coverage agent is loaded and Mockito once again warns me to add it as an agent to the build.
However, if adding it via `jvmArgs("-javaagent:${mockitoAgent.asPath}")`, I can confirm that running it with IntelliJ coverage fails. In that case `gradle test --info` shows both the Mockito and IntelliJ Java agents

**Comment by bric3** [comment]
By the way this is already fixed.
https://github.com/mockito/mockito/commit/d01ac9d8222b01d6694b11a9978a91eb9aced5b1

**Comment by rkrisztian** [comment]
Please note that you should use [lazy configuration](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#eager_apis_to_avoid) to prevent unnecessary task object creations when not needed. So for example (in Kotlin DSL):

```kotlin
tasks.named<Test>("test") { /* ... */ }
tasks.withType<Test>().configureEach { /* ... */ }
```

By the way, the 2nd alternative is more comprehensive, as people may use mocking on multiple test types/levels.

Same is true for [creating dependency configurations](https://docs.gradle.org/current/userguide/declaring_configurations.html#header).

**Update:** This is the code I use in Kotlin DSL:

```kotlin
val mockitoAgent by configurations.registering

dependencies {
	mockitoAgent("org.mockito:mockito-core") { isTransitive = false }
}

tasks.withType<Test>().configureEach {
    jvmArgs("-javaagent:${mockitoAgent.get().asPath}")
}
```

* Mockito version omitted in my case due to the Spring Dependency Management plugin, normally referencing the version catalog is better.
* Not using any incubating API.
* Tested with Gradle 9.4.1.

**Comment by CC007** [comment]
> When using `jvmArgs.add("-javaagent:${mockitoAgent.asPath}")`, only the IntelliJ coverage agent is loaded and Mockito once again warns me to add it as an agent to the build. However, if adding it via `jvmArgs("-javaagent:${mockitoAgent.asPath}")`, I can confirm that running it with IntelliJ coverage fails. In that case `gradle test --info` shows both the Mockito and IntelliJ Java agents

Can confirm. When using a run configuration in IntelliJ, I still get the warning with `jvmArgs.add(...)`, but the problem is resolved when using `jvmArgs(...)`

**Comment by bric3** [comment]
Thanks for information, I'd to mention the notable difference between the Groovy DSL and the Gradle Kotlin DSL.

```Gradle
// build.gradle
// Materializes the Test task, eager
tasks.test { }
```

```Gradle Kotlin DSL
// build.gradle.kts
// TaskProvider<Test>, generated accessor calling under the hood tasks.named("test"), lazy
tasks.test { }
```

`tasks.withType<Test>().configureEach { }` is fine, but might be unnecessary for simple projects, in order to avoid going down the Gradle intricacies I made the call to keep the doc simple.

**Comment by rkrisztian** [comment]
Hi, @bric3,

> ```kotlin
> // build.gradle.kts
> // TaskProvider<Test>, generated accessor calling under the hood tasks.named("test"), lazy
> tasks.test { }
> ```

Thanks, I learned something new today. I wish this was documented clearly in https://docs.gradle.org/current/userguide/task_configuration_avoidance.html, but I couldn't find anything related.
